//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpMaster
    {
        public int EmpID { get; set; }
        public string EmpNo { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string SurName { get; set; }
        public string PassportName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string BirthPlace { get; set; }
        public string Gender { get; set; }
        public string ContactPerson { get; set; }
        public string Nationality { get; set; }
        public string BloodGroup { get; set; }
        public string MaritialStatus { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> rec_status { get; set; }
    }
}
