//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrgMaster
    {
        public int OrgId { get; set; }
        public string OrgName { get; set; }
        public string RegAddress { get; set; }
        public string CorpAddress { get; set; }
        public System.DateTime Date { get; set; }
    }
}
